name: CI/CD Pipeline

on:
  push:
    branches:
      - final

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Log in to Amazon ECR
      run: |
        aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 548895127859.dkr.ecr.us-east-1.amazonaws.com

    - name: Build and push Docker image
      run: |
        docker build -t 548895127859.dkr.ecr.us-east-1.amazonaws.com/my-ecr-repository:latest .
        docker push 548895127859.dkr.ecr.us-east-1.amazonaws.com/my-ecr-repository:latest

    - name: Run ECS Task
      run: |
        aws ecs run-task \
          --cluster my-ecs-cluster \
          --task-definition my-task-definition \
          --launch-type EC2 \
          --count 1 \
          --subnet subnet-0347b0de938a628bb \
          --security-group sg-0123456789abcdef0
