name: Deploy to AWS ECS

on:
  push:
    branches:
      - final  # Triggers deployment when code is pushed to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Ensure this matches your AWS region

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Tag Docker Image
        run: |
          ECR_REPO_URI=548895127859.dkr.ecr.us-east-1.amazonaws.com/flask-app
          docker build -t $ECR_REPO_URI:latest .
          echo "ECR_REPO_URI=$ECR_REPO_URI" >> $GITHUB_ENV

      - name: Push Docker Image to Amazon ECR
        run: |
          docker push ${{ env.ECR_REPO_URI }}:latest

      - name: Deploy New Image to ECS
        run: |
          aws ecs update-service --cluster flask-cluster --service flask-service --force-new-deployment
